### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by 674273563** [abcfy2/getComic#11]
下载了getComic-1.6.zip 
然后呢？

**Comment by abcfy2** [comment]
你下载的是源码，按照首页README的说明安装运行环境依赖即可(python3, python3-request, python3-pyqt5)。至于windows打包版本暂时不可用了，我的windows虚拟机被干掉了，也就没有windows的打包环境了，很久没有维护那个了。下次用windows做开发环境的时候再抽空搞一下吧。

我现在主要用linux做开发环境了

**Comment by abcfy2** [comment]
新版本的windows bundle打包完毕，请从README上的链接下载。

如有问题，欢迎反馈

**Comment by 674273563** [comment]
腾讯漫画没什么日漫啊 能支持动漫屋吗？

**Comment by abcfy2** [comment]
腾讯动漫算是最早买入正版日漫授权的吧？其他网站的支持暂时没做，主要是个人精力问题。如果还有闲暇时间的话，可能会考虑重构代码，添加其他网站支持，统一接口。

**Comment by abcfy2** [comment]
瞅了下，动漫屋似乎大部分日漫链接用的是腾讯动漫的，而且空间都被封了，有必要做支持么？

**Comment by 674273563** [comment]
腾讯漫画很多青年类漫画都没有的

**Comment by 674273563** [comment]
魔偶马戏团_ 破坏王 月光条例_草莓棉花糖 都没

**Comment by 674273563** [comment]
甚至浪客行都-----

**Comment by 674273563** [comment]
动漫之家怎样？

**Comment by abcfy2** [comment]
如果有时间追漫画的话，也许会考虑重构一下代码，方便加入更多网站的支持。
