### ISSUE TITLE
好像下不了番外？

### ISSUE THREAD

**Issue by wby238** [abcfy2/getComic#12]
最近想补一下[银魂](http://ac.qq.com/Comic/comicInfo/id/505435)，然而番外并没有下到（分析中也没有）
虽然番外只有几话

**Comment by abcfy2** [comment]
这个和火影彩版一样，在pc端页面上，你会看到顶上的地址栏是共享一个ID的，我的程序是根据这个漫画的id拿到对应的漫画信息的，在PC端页面上显然你做不到。

只能从移动端的页面上去搜索，在移动端的页面(m.ac.qq.com)上你会发现这两个漫画是不同的id，分析移动端的漫画页面就行了: http://m.ac.qq.com/comic/index/id/531615

**Comment by wby238** [comment]
哦，thx
不过好像有些图片下载不完整啊……
看的时候某几张图片都有一大部分损坏了……
虽然占的比例不多

**Comment by abcfy2** [comment]
我这边倒是没有遇到。有没有中断下载呢？中断下载的图片是不会续传的(这个算法没实现)，程序会判断目标文件是否存在，存在则跳过下载，实现了伪续传，对于本身就没下载完整的图片就爱莫能助了，只能手工删掉之后重新运行程序补上。

**Comment by wby238** [comment]
没有中断过下载，也就几张而已，到时候手动删掉补就行了，thx
