### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by TwoWater** [abcfy2/getComic#13]
可以模拟登录吗？爬 VIP 的动画

**Comment by abcfy2** [comment]
不想费劲的解决验证码问题，所以暂不考虑。

再加上普通用户可能对这种不知名的登录会有恐惧感，做了也不见得有人会使用这种“第三方”的登录方式，害怕会有泄密的风险。

因此最初设计的时候我就没打算把登录功能加进去，实在觉得没必要，不想把一个简单的小功能做的太繁琐，也不想做的太过。
