### ISSUE TITLE
你好，我想问一下如果模拟cookie该怎么做？

### ISSUE THREAD

**Issue by shfxxer** [abcfy2/getComic#14]
RT，有些漫画是收费漫画，我倒是有个付费帐号，现在想用这个帐号下载付费章节该怎么做？

**Comment by abcfy2** [comment]
目前没做cookie导入，你可以参考https://github.com/abcfy2/getComic/issues/5#issuecomment-223790254 这个回复，最简单的做法还是从腾讯动漫的app上下载。

如果非要用这个程序做的话，恐怕只能改源码了，https://github.com/abcfy2/getComic/blob/master/getComic.py#L73 把你的cookies字符串update到这里，尝试执行。

**Comment by shfxxer** [comment]
非常感谢，因为app没用过所以不太清楚，不过他们这种下载下来都不太会是jpg模式吧，我倒是有几个用习惯的阅览器了。回去试试看复制cookie吧

anyway，感谢您的贡献。

**Comment by abcfy2** [comment]
我看了下app离线下载，确实不是jpg，但我观察发现其实是jpg之前填充了一些自己的元数据罢了。我尝试对照着jpg的文件格式(0xFF D8 FF E0开头)，找到了被填充的部分，手工删除前面这段填充内容，从jpg文件头开始保留，发现就可以打开jpg图片了。有时间写个脚本处理下吧。暂时没发现什么好办法排序
