### ISSUE TITLE
关于获取腾讯漫画网站中的json内容

### ISSUE THREAD

**Issue by yanhuibin315** [abcfy2/getComic#16]
我尝试着用java获取腾讯漫画网站的代码，但获取漫画内容时候得到的图片
<img src="{{firstPicState}}" data-pid="{{$value.pid}}" data-w="{{$value.width}}" data-h="{{$value.height}}" class="loaded" alt=""/>
格式是这种，想知道如何解决呢？谢谢

**Comment by abcfy2** [comment]
图挂了

**Comment by yanhuibin315** [comment]
开发过程中我用Chrome的开发工具查看发现，我得到的source中这种格式的文本 <img src="{{firstPicState}}" data-pid="{{$value.pid}}" data-w="{{$value.width}}" data-h="{{$value.height}}" class="loaded" alt=""/>
                但我想要获取到elements中http://ac.tc.qq.com/store_file_download?buid=15017&uin=1422393807&dir_path=/&name=28_05_23_28ca52ab3ada9f6e1e0f1df6004fd336_17848.ori这种具体的src值，想知道是什么原因？

**Comment by abcfy2** [comment]
那段dom不是直接写在页面源码上的，而是经过js执行渲染过的，如果你页面打断点就可以发现了

**Comment by yanhuibin315** [comment]
ok, thank you
