### ISSUE TITLE
已经失效了哦。。

### ISSUE THREAD

**Issue by zhhr1122** [abcfy2/getComic#18]
之前一直都能使用，最近突然不行了，不知道您有没有时间去修复修复呢？我用了你项目原理作为我的项目的接口，现在突然使用不了，希望您能抽空修复下~谢谢咯，另外下面是我项目的地址，采用的是您的接口，也欢迎和我联系。

https://github.com/zhhr1122/z_comic_new

**Comment by abcfy2** [comment]
腾讯移动端的页面接口改了，之前是把章节信息全部放在XHR拿到的json中，现在看来是直接写到页面中去了，原来的那个XHR现在报404了。

我看看有没有优雅点的办法解决，时间不能保证。

**Comment by zhhr1122** [comment]
辛苦作者了！看您的代码和文章受益匪浅，也一直在用您的接口作为项目接口，希望能解决

**Comment by abcfy2** [comment]
其实有个可能很长时间都有效的办法，就是利用腾讯动漫app android的离线下载功能。差不多它的算法我都搞清楚了，就是每个jpg文件头塞入了若干个字节(没仔细统计过)，导致图片浏览器不识别，去掉这些被塞进去的混淆字节就可以用图片浏览器打开了。

这个可能麻烦点，但是估计长期有效。就是得从官方app把下载的目录全部导出来，在本地写个脚本去处理(Linux下的dd --seek目测都能搞定，只要能确定填充的字节数)

**Comment by zhhr1122** [comment]
您之前的代码也算长时间有效了，大概一年左右吧，都比较有效，腾讯一般也不太会去轻易更新的。
另外题外话，很谢谢作者啊，用您的算法我自己用flask-restful生成了API接口，然后开发成了APP,成功找到了工作，现在从事Android漫画相关开发工作，还是挺感谢您的！

**Comment by abcfy2** [comment]
fixed. 图形化界面程序就懒得打包了，好久不用python打包了，都不知道cx_freeze和pyinstaller进化到什么程度了，以前的build脚本也找不到了，就懒得在windows下提供打包好的程序了。

腾讯基本上把页面上的XHR全废掉了，改到了渲染到页面上。不得已，只要加上废弃很久的依赖lxml了，通过lxml的xpath解析html页面元素。本来解析的都是pc页面的，但是发现pc页面当漫画章节少到没有分页时(比如这个: http://ac.qq.com/Comic/comicInfo/id/633890)，页面章节列表布局不一样。懒得写两个xpath了，就干脆改到移动端的章节列表页面上: https://m.ac.qq.com/comic/chapterList/id/547278 这个页面无论章节多少都是有内容的，并且布局一样，一个xpath可以搞定。缺点是在章节列表页面上无法获取章节名字，因为这些按钮上的章节名字全是数字，我也很绝望啊。
