### ISSUE TITLE
改版后画质下降了！

### ISSUE THREAD

**Issue by kodoking** [abcfy2/getComic#20]
腾讯漫画有两种清晰度：
1、电脑的网页版，1100宽的分辨率
2、手机的网页版或APP端，800宽的分辨率
以前都能下载1100宽的高清图，前几天程序失效，我换了新版getComic试验了下，发现画质下降了，下载的图片由1100宽的高清图变成了800宽的一般画质了……

**Comment by abcfy2** [comment]
从来没注意PC端和移动端用的分辨率不一样。 前段时间因为这个issue https://github.com/abcfy2/getComic/issues/18 重写了爬取接口，当时为了省事用了移动端的页面解析，因为PC端的页面在章节少和章节多的场景下页面样式不一样，但是移动端是统一的，所以统一用了移动端的页面下载的漫画。

**Comment by abcfy2** [comment]
确认了下，我用PC端看了下最新的一人之下漫画，确实是800px的，还有野良神的PC端漫画也是800px的。你找找看哪些漫画还有1100px的？如果有的话用我的工具下载下来还是800px的吗？

**Comment by kodoking** [comment]
野良神我今天刚从浏览器用扒图工具下了，是1100px的：
链接: https://pan.baidu.com/s/1PXQrMqexlQsd-TuO6IiilQ 密码: 9ssc
（01-74话是以前用你的软件下的，75话是今天用浏览器扒图插件下的）

**Comment by abcfy2** [comment]
好像的确是这样，移动端和PC端返回的分辨率是不一样的，我把页面改到PC端页面吧。野良神的75话开始是1100px的，第一话的确只有820px。在移动端似乎都缩放成了800px

**Comment by abcfy2** [comment]
另外发现如果要下载收费漫画，需要在cookie中包含三个key: ` uin=xxxxx; ptisp=ctc; skey=@xxxxx`，暂时没细细研究这三个值是怎么得到的，感觉`ptisp`应该是固定的，其他两个是怎么算出来的暂时没精力研究

**Comment by abcfy2** [comment]
Fixed. 解析页面改到了ac.qq.com
