### ISSUE TITLE
脚本貌似失效了？

### ISSUE THREAD

**Issue by ckz1211** [abcfy2/getComic#22]
下载总是失败（重试）——失败（重试）：
http://ac.qq.com/Comic/comicInfo/id/634670

**Comment by abcfy2** [comment]
应该是腾讯把页面上base64的解析算法改了。

比如任意一页的漫画页: http://ac.qq.com/ComicView/index/id/634670/cid/2

中的源码，都能找到类似的:

```html
<script>
    var DATA        = 'eyJjb21pYyI6ecyJpZCI6NjM0NjcwLCJ0aXRsZbcSI6Ilx1NGYwYVx1NzUzOFx1NjYxZlx1NTM5ZiBFREVOUyBaRVJPIiwcffiY29sbGVjdCI6IjMwMTUiLCJpc0phcGFuQ29taWMfiOmZhbHNlLCJpc0xpZ2h0Tm92ZWwiOmZhbHNlLCJpc0xpZ2h0Q29taWMiOmZhbHNlLCJpc0ZpbmlzaCI6ZmFsc2UsImlzUm9hc3RhYmxlIjp0cnVlLCJlSWQiOiJLbEJQVEVKQlZGUlZDUXNmQWdZQ0FROEpIRUl5In0sImNoYXB0ZXIiOnsiY2lkIjoyLCJjVGl0bGUiOiJcdTY1NmNcdThiZjdcdTY3MWZcdTVmODUiLCJjU2VxIjoiMSIsInZpcFN0YXR1cyI6MSwicHJldkNpZCI6MCwibmV4dENpZCI6NCwiYmxhbmtGaXJzdCI6MSwiY2FuUmVhZCI6dHJ1ZX0sInBpY3R1cmUiOlt7InBpZCI6IjcwMjgiLCJ3aWR0aCI6MTEwMCwiaGVpZ2h0Ijo1NDgsInVybCI6Imh0dHBzOlwvXC9tYW5odWEucXBpYy5jblwvbWFuaHVhX2RldGFpbFwvMFwvMjZfMTBfNTZfZTZjMDhhMzMxNGE4MTY4MThmOGI0NTM4OTY0ODAwZjVfNzAyOC5qcGdcLzAifV0sImFkcyI6eyJ0b3AiOiIiLCJsZWZ0IjpbXSwiYm90dG9tIjp7InRpdGxlIjoiXHU5MDFhXHU3MDc1XHU1OTgzXHU2NzA5XHU1OGYwXHU2ZjJiXHU3NTNiIiwicGljIjoiaHR0cHM6XC9cL21hbmh1YS5xcGljLmNuXC9vcGVyYXRpb25cLzBcLzA3XzEyXzM2X2UyNjY2ZGQ4NTFiMzY1M2NlMDAxMjRkMDk2ZjdlYjEyXzE1NDE1NjU0MDYxODguanBnXC8wIiwidXJsIjoiaHR0cHM6XC9cL3YucXEuY29tXC94XC9wYWdlXC94MDc4NjJrd2VsaS5odG1sIiwid2lkdGgiOiI2NTAiLCJoZWlnaHQiOiIxMTAifX0sImFydGlzdCI6eyJhdmF0YXIiOiJodHRwOlwvXC90aGlyZHFxLnFsb2dvLmNuXC9nP2I9c2RrJms9NjlpY1gwNzFZT0xRZ0R2RVJ1MmhMVHcmcz02NDAmdD0xNDgzMzY2MTE5IiwibmljayI6Ilx1OGJiMlx1OGMwOFx1NzkzZVx1NTMxN1x1NGVhYyIsInVpbkNyeXB0IjoiYUc5elZ6SXplV2RFY0hnMldVUXlVbkUyWm14WWR6MDkifX0=',
        PRELOAD_NUM = 2,
        NOTICE_TIME = 15,
        ROAST_SIZE  = 300,
        ROAST_PRE   = 5,
        ROAST_VIEW  = 11,
        DANMU_TIME  = 10000;
</script>
```

这个`DATA`变量中存储的实际是包含了章节图片的json，但是不能直接解析。以前的算法是移除第一个字母后，其余字符串便是标准的Base64。目前看来改了，这个Base64无法解析，需要在页面打断点，找到具体的解析算法了。

**Comment by ckz1211** [comment]
有办法在页面的JS函数里找到解密base64的相关段落么？

**Comment by ckz1211** [comment]
也就是说js打断点的方法局限性很大？没法直接找到具体是哪个函数负责解密？

**Comment by abcfy2** [comment]
也不算太难，就是要有耐心。在开发者工具中格式化js代码，一个函数一个函数打断点，基本很快就能找到

**Comment by abcfy2** [comment]
而且我已经找到了:
![image](https://user-images.githubusercontent.com/5327677/48149167-6b032300-e2f6-11e8-82c1-5e22b4382362.png)

的确如我所料，就是那个js中，这个`_v`变量存储着`DATA`解析后的json，只要向上找应该就能很快找到具体解析算法了。

**Comment by abcfy2** [comment]
我知道了，打断点再加上格式化，已经找到这段算法了，js代码大致如下:

```js
T = W['DATA'].split(''),
N = W['nonce'],
len,
locate,
str;
N = N.match(/\d+[a-zA-Z]+/g);
len = N.length;
while (len--) {
  locate = parseInt(N[len]) & 255;
  str = N[len].replace(/\d+/g, '');
  T.splice(locate, str.length)
}
T = T.join('');
_v = JSON.parse(B.decode(T));
```

关键在于`T`变量和`N`变量，`T`变量的数值来自于页面的`DATA`部分，而`N`变量来自于页面的`window.nonce`部分，经过下面那一段解密算法还原正确的base64就可以了，只要把这段js代码翻译为python就搞定了。

**Comment by abcfy2** [comment]
fixed. 多谢反馈

**Comment by ckz1211** [comment]
居然又失效了……http://ac.qq.com/Comic/comicInfo/id/634670

**Comment by abcfy2** [comment]
看来`http://ac.qq.com/Comic/comicInfo/id/{}`这个接口被废弃掉了，等有时间了看看现在页面是怎么拿到漫画章节列表的吧。

**Comment by nhacvina** [comment]
getComic.py -u http://ac.qq.com/Comic/ComicInfo/id/634393

正在下载第0001话: 预告
下载失败，重试1次
下载失败，重试2次
下载失败，重试3次
下载失败，重试4次
Traceback (most recent call last):
  File "./getComic.py", line 338, in <module>
    main(url, path, lst, one_folder)
  File "./getComic.py", line 294, in main
    imgList = getImgList(contentList[i - 1]['url'])
  File "./getComic.py", line 105, in getImgList
    img_detail_json = __decode_data(data, nonce)
  File "./getComic.py", line 166, in __decode_data
    json_str = base64.b64decode(base64_str).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 7: invalid start byte

**Comment by abcfy2** [comment]
已知问题。最近暂时没时间细细研究页面更改。感觉已经被腾讯盯上了，我这边一改那边立刻就改。欢迎递交PR解决。
