### ISSUE TITLE
关于nonce的值

### ISSUE THREAD

**Issue by andy-GGY** [abcfy2/getComic#25]
大佬，nonce的值始终没看懂怎么得出的，请指教

**Comment by abcfy2** [comment]
很久没更新了，因为跟TX斗智斗勇太长时间，心累了。我感觉之前这个脚本被TX盯上了，我当时每更新一版页面上的`nonce`算法就更新一次，后来实在太忙了就没精力再去看它的页面上的逻辑算法了。

最早这个`nonce`是直接在页面上的<script>标签就生成的，script标签中的js代码直接就是`nonce = "xxxxxxx";`，用正则就能抓出来。

后来改成了欺骗性质的，页面上会有好几个地方都有`nonce = "xxxxxx";`你得抓取最后一个赋值的地方，那个才是真正生效的。不过这个也难不倒正则表达式，依旧可以通过正则全部抓取然后分组取最后一个。

上一次我改算法的时候大概是这样的:

```js
nonce = "str1" + "xxxx" + "str2";
```

更绝了，甚至中间的空格数量还是随机的，加号拼接字符串还是多行的，可能会折行到好几行，不过由于是用`+`拼接的字符串，所以我上一次的逻辑应该是把所有的换行符，加号，引号这里正则全部去掉，所以你看到的那个正则和逻辑可能会比较奇怪，取了个巧而已。被正则处理过大概这里会变成类似于这样:

```js
nonce=str1xxxxxstr2;
```

再次用正则提取就可以了拿到真正的`nonce`，不过这种算法不具有通用性，如果页面再变肯定还得改算法。这几年事情比较多，很少看腾讯漫画了，也暂时没精力再看看它的页面到底改成啥样了。

**Comment by andy-GGY** [comment]
感谢大佬回复，原来TX还有这种操作，看来匹配还是正则靠谱，我还要继续努力，谢谢

**Comment by abcfy2** [comment]
想发现它的算法其实也不算难，就是要有耐心。

我当时也是用chrome开发者工具在页面打断点逐步发现的。最早正则抓取是没问题的，但是打断点就发现页面上的nonce和最终执行完毕之后变量列表显示的nonce不一致，然后逐步打断点逐步缩小代码范围就可以了定位到具体的函数，细读这一部分函数就可以了拿到真正的算法，再用python把这一部分js的逻辑实现了就OK了

**Comment by abcfy2** [comment]
比如这样的。随手打了个断点，扫一眼代码凭感觉打了个断点:

![深度截图_选择区域_20200427224602](https://user-images.githubusercontent.com/5327677/80385755-0a481b80-88d9-11ea-88de-b220507904be.png)

可以看到右边的变量已经有`nonce`了，说明在这段代码之上的部分就已经生成了这个变量，逐级向上，观测一下nonce生成过程，就能发现它的算法了，就是需要耐心，我当时找它页面上nonce的算法的时候差不多也花了一整天。

之所以用`m.ac.qq.com`这个域名下找也是因为这个给移动端用的页面相对好爬取，一直没有flash，最早的`ac.qq.com`可是有flash的，根本没办法解析

**Comment by andy-GGY** [comment]
js逆向找到生成规则还不要紧，按照之前的习惯扣代码然后运行，经过多次失败，重新读js代码，才注意到这个nonce值是个要命的地方，xpath也罢，re也罢，运行起来就是与想要的结果不匹配，而且TX更过分的是页码上也动了手脚，没有第四页，太机智了，呵呵

**Comment by abcfy2** [comment]
对的，这个`nonce`规则经过几次混淆了，直接肯定是没法从页面源码中通过正则抓取的。

我记得我最后一次改动的时候这里最绝的大概类似于是这样搞的:

```js
eval("no" + "n" + "" + "ce" + "="+...);
```

牛逼不？直接用`eval`把`nonce`的赋值过程用字符串拼接的形式拼出来（现在规则肯定改了），一般的正则很难解析这里。

所以你需要像我上面那样一点一点打断点抓出来新的算法

**Comment by e-hoarder** [comment]
I didn't really rigorously test this but I got the nonce to work with this little change

```
12a13
> import execjs
90a92,102
> def get_nonce_script(strings):
>     pattern = re.compile(r'^window\["n.*e"\]\s*=(.*)')
>     for string in strings:
>         match = pattern.match(string)
>         if match:
>             return match.group(1).strip()  # Return the captured group value
>     return None
> 
> def evaluate_js(code):
>     context = execjs.compile(f'result = {code}')
>     return context.eval('result')
100c112,117
<             nonce = re.findall(r'data-mpmvr="(.+?)"', chapter_page)[0]
---
>             # nonce = re.findall(r'data-mpmvr="(.+?)"', chapter_page)[0]
>             scripts = html.fromstring(chapter_page).xpath('//script/text()')
>             nonce = get_nonce_script(scripts)            
>             nonce = evaluate_js(nonce)
>             print(nonce)
>             
```
I'll leave this here in case it helps anyone else
