### ISSUE TITLE
picJsonPage is empty

### ISSUE THREAD

**Issue by markwithk** [abcfy2/getComic#3]
It gets empty picJsonPage, thus json.loads(picJsonPage) raises exception.

**Comment by abcfy2** [comment]
Ok. Maybe tencent comic has changed its page structure. I'll fix this issue, wait please.

**Comment by abcfy2** [comment]
I've found the reason. Because the picJsonPage url like ``http://pad.ac.qq.com/View/mGetPicHash?id=512991&cid=27`` must request with ``cookie``, otherwise it will return nothing.

So I will parse the ``cookie``, it may take some times.

**Comment by abcfy2** [comment]
Bug fixed. Please check 33437ec271cde07b45316139ccf1403aa44217ea.

Cookie must contains ``ac_refer=``.

Please checkout the latest code and try again.

Windows bundle package is uploading.

**Comment by markwithk** [comment]
Good job!
May I ask you how did you find the reason and what tools did you use?

**Comment by abcfy2** [comment]
Chrome ``F12 developer tools`` and Firefox ``[firebug](http://getfirebug.com/)`` add-on is my friend.

Also, the commend tool ``[curl](http://curl.haxx.se/)`` is an awesome tool.

Curl can simulate and fake the browser request, it's helpful when debug the request headers.

When I use ``curl -v http://pad.ac.qq.com/View/mGetPicHash?id=512991&cid=27``, return nothing, but chrome works well. So I compare the headers between curl and chrome, and finally I've found ``curl -v -H 'Cookie:xxxxxxxxxxxx(copy from chrome)'`` can get the json string. Then I know must request with ``Cookie``. But the cookie string is too long, so I use firefox and open firebug to check the cookie. After flush all cookies, I've found that when the cookie add the ``ac_refer`` field, picjsonpage will return json string. After all, use curl to verify. ``curl -v -H 'Cookie: ac_refer=http://pad.ac.qq.com/Comic/comicInfo/id/512991' 'http://pad.ac.qq.com/View/mGetPicHash?id=512991&cid=27'`` and it works.

**Comment by markwithk** [comment]
Cool!
Thanks.
