### ISSUE TITLE
现在还能爬取腾讯漫画吗？ 腾讯已经做了反爬取了吧？

### ISSUE THREAD

**Issue by guozhouwei** [abcfy2/getComic#5]
RT.

**Comment by abcfy2** [comment]
刚测试了一下，还可以用。不过只能下载免费漫画，收费漫画只能下载第一张图。

**Comment by abcfy2** [comment]
话说回来，腾讯是做过反爬处理，我的算法已经改过好几次了。第一个版本是可以爬取收费漫画的(因为页面的Ajax没做验证，可以直接返回收费漫画的图片地址)，后来改过几次之后，收费漫画就再也不能直接下载了(我也懒的做登录了，估计用的人也不会买涨，毕竟要扣钱的，而且未必会信任)。

**Comment by guozhouwei** [comment]
@abcfy2 
非常感谢您的神速回复！ 那我就用这个了哈～

**Comment by mengmo** [comment]
@abcfy2 

> 我也懒的做登录了

那么，能不能借鉴一下 `you-get` 的做法，调用 `cookies` 呢？

**Comment by abcfy2** [comment]
这样的话恐怕大多数用户都不知道怎么用。现在化的浏览器都会加密自己的cookies文件，从外部难以直接获取。那么就只能从浏览器的开发者工具自己复制出cookie字符串，考虑到这里对大多数用户来说实在有点难度。另外，登录目前来说挺鸡肋的，也就是下载已付费的漫画有点用，不过，下载已付费的漫画这里就已经是官方app的强项了，我也就没必要重复造轮子。这个小工具的初衷只是为了自己在pc上追漫画方便点。随着腾讯动漫官方app不断完善，在移动设备上追漫画也挺方便的了。
