### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by guozhouwei** [abcfy2/getComic#6]
![image](https://cloud.githubusercontent.com/assets/16585863/15245130/651223c8-1937-11e6-8685-3c72c5a1fc7b.png)

嗨 遇到个问题，这是报什么错误？ 我没用过python，我的电脑事mac。

**Comment by abcfy2** [comment]
没装pyqt5

**Comment by abcfy2** [comment]
这个问题解决了么？如果已经解决，我会关闭这个issue，感谢反馈
