### ISSUE TITLE
getComic.py pulling first image for all images

### ISSUE THREAD

**Issue by Hackswell** [abcfy2/getComic#7]
When trying to download 小倩投食计划, it pulled 34 chapters.... but every picture was the cover photo.

./getComic.py -u http://ac.qq.com/Comic/comicInfo/id/540361

**Comment by abcfy2** [comment]
Tencent has changed its page structure. So my program could not work any more. And I have no enough time to fix issue, it's a little hard to solve. Sorry.

But if I have time, I will try to fix this issue.

**Comment by abcfy2** [comment]
If you really like Chinese manhua on tencent commit, I would like to recommend you have a try the official app 腾讯动漫: http://mobile.ac.qq.com/index.html. It can also download offline.

**Comment by abcfy2** [comment]
Good news, I'm fixed this issue. Please pull the latest code then try again.
