### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by Hackswell** [abcfy2/getComic#8]
Is it possible to have a command-line switch for a http proxy?  I've hard-coded it, but it's ugly, and Python isn't my preferred language. 

proxy = '120.52.72.24:80'
proxies = { 'http' : 'http://'+proxy }
requestSession.proxies.update(proxies)

**Comment by abcfy2** [comment]
Not yet. But you could try [proxychains-ng](https://github.com/rofl0r/proxychains-ng)

**Comment by abcfy2** [comment]
If I have enough times, I will consider to refector my codes to add more manhua sites easily. And may be I could support proxy. Thanks.
