### ISSUE TITLE
Error if chapters more 99

### ISSUE THREAD

**Issue by JustPlainUser** [abcfy2/getComic#9]
get error: 
Traceback (most recent call last):
  File "getComic.py", line 320, in <module>
    main(url, path, lst, one_folder)
  File "getComic.py", line 278, in main
    imgList = getImgList(contentList[i - 1], id)
  File "getComic.py", line 90, in getImgList
    base64data = re.findall(r"data:\s*'(.+?)'", cid_page)[0][1:]

any comic where more 99 chapters.

**Comment by abcfy2** [comment]
Did you use the latest code? If so, please show me the console that let me know which manhua in tencent comic you try to download.

**Comment by JustPlainUser** [comment]
for example i try this comic (output in file)

[output-error.txt](https://github.com/abcfy2/getComic/files/393663/output-error.txt)

**Comment by abcfy2** [comment]
I know the reason, wait please. I will try to fix this issue.

**Comment by abcfy2** [comment]
Fixed. Please checkout the latest code and try again. Let me know if your have any other issues.

Thanks for your reporting.
